// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DeprecatedProxyConfigApplyConfiguration represents a declarative configuration of the DeprecatedProxyConfig type for use
// with apply.
type DeprecatedProxyConfigApplyConfiguration struct {
	FloatingUserId *bool `json:"floatingUserId,omitempty"`
}

// DeprecatedProxyConfigApplyConfiguration constructs a declarative configuration of the DeprecatedProxyConfig type for use with
// apply.
func DeprecatedProxyConfig() *DeprecatedProxyConfigApplyConfiguration {
	return &DeprecatedProxyConfigApplyConfiguration{}
}

// WithFloatingUserId sets the FloatingUserId field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FloatingUserId field is set to the value of the last call.
func (b *DeprecatedProxyConfigApplyConfiguration) WithFloatingUserId(value bool) *DeprecatedProxyConfigApplyConfiguration {
	b.FloatingUserId = &value
	return b
}
