// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// KubernetesProxyFullConfigApplyConfiguration represents a declarative configuration of the KubernetesProxyFullConfig type for use
// with apply.
type KubernetesProxyFullConfigApplyConfiguration struct {
	KubernetesProxyConfigApplyConfiguration `json:",inline"`
	DeprecatedProxyConfigApplyConfiguration `json:",inline"`
}

// KubernetesProxyFullConfigApplyConfiguration constructs a declarative configuration of the KubernetesProxyFullConfig type for use with
// apply.
func KubernetesProxyFullConfig() *KubernetesProxyFullConfigApplyConfiguration {
	return &KubernetesProxyFullConfigApplyConfiguration{}
}
